addLayer("achievements", {
    name: "Achievements", // This is optional, only used in a few places, If absent it just uses the layer id.
    symbol: "Ach", // This appears on the layer's node. Default is the id with the first letter capitalized
    row: "side",
    position: 0, // Horizontal position within a row. By default it uses the layer id and sorts in alphabetical order
    startData() { return {
        unlocked: true,
    }},
    achievements: {
        1: {
            name: "First Reset<br><small>(of many)</small>",
            image: "resources/achievements/1_01.png",
            tooltip: "<h3>First Reset <small>(of many)</small></h3><hr style='margin-bottom:4px'>Obtain your first rank.",
            color: "white",
            complete() {return hasUpgrade("p", 17)},
            unlocked: true,
        },
        2: {
            name: "Small Beginnings",
            image: "resources/achievements/1_02.png",
            tooltip: "<h3>Small Beginnings</h3><hr style='margin-bottom:4px'>Obtain your first tier.<br><br>Reward: Ranks are 20% cheaper.",
            color: "white",
            complete() {return hasUpgrade("p", 18)},
            unlocked: true,
            marked: true,
        },
        3: {
            name: "Seperate Doubling",
            image: "resources/achievements/1_03.png",
            tooltip: "<h3>Seperate Doubling</h3><hr style='margin-bottom:4px'>Reach x2 points from factors.",
            color: "white",
            complete() {return hasUpgrade("p", 15) || hasUpgrade("cs", 201)},
            unlocked: true,
        },
        4: {
            name: "Tetr, Hold the Mino",
            image: "resources/achievements/1_04.png",
            tooltip: "<h3>Tetr, Hold the Mino</h3><hr style='margin-bottom:4px'>Obtain your first tetr.<br><br>Reward: Ranks and Tiers are<br>15% cheaper.",
            color: "white",
            complete() {return hasUpgrade("p", 22) || hasMilestone("s", 19)},
            unlocked: true,
            marked: true,
        },
        5: {
            name: "Prestigious",
            image: "resources/achievements/1_05.png",
            tooltip: "<h3>Prestigious</h3><hr style='margin-bottom:4px'>Do your first prestige reset.<br><br>Reward: Ranks, Tiers, and Tetrs<br>are 10% cheaper.",
            color: "white",
            unlocked: true,
            marked: true,
        },
        6: {
            name: "Octuple Factors",
            image: "resources/achievements/1_06.png",
            tooltip: "<h3>Octuple Factors</h3><hr style='margin-bottom:4px'>Buy a Factor VIII.",
            color: "white",
            complete() {return hasUpgrade("p", 15) || hasUpgrade("cs", 201)},
            unlocked: true,
        },
        7: {
            name: "Factor Powered",
            image: "resources/achievements/1_07.png",
            tooltip: "<h3>Factor Powered</h3><hr style='margin-bottom:4px'>Buy a Power Factor.",
            color: "white",
            complete() {return hasUpgrade("p", 21) || hasUpgrade("cs", 201)},
            unlocked: true,
        },
        8: {
            name: "Leaf Leavings",
            image: "resources/achievements/1_08.png",
            tooltip: "<h3>Leaf Leavings</h3><hr style='margin-bottom:4px'>Buy a Leaf Producer.",
            color: "white",
            complete() {return hasMilestone("r", 12)},
            unlocked: true,
        },
        9: {
            name: "Longer Blades",
            image: "resources/achievements/1_09.png",
            tooltip: "<h3>Longer Blades</h3><hr style='margin-bottom:4px'>Increase your grass value.<br><br>Reward: Grass spawn time<br>reduced by 10%.",
            color: "white",
            complete() {return hasMilestone("r", 13)},
            unlocked: true,
            marked: true,
        },
        10: {
            name: "Pent Up",
            image: "resources/achievements/1_10.png",
            tooltip: "<h3>Pent Up</h3><hr style='margin-bottom:4px'>Obtain your first pent.",
            color: "white",
            complete() {return hasUpgrade("i", 32) || inChallenge("ip", 14)},
            unlocked: true,
        },
        11: {
            name: "Natural Dormancy",
            image: "resources/achievements/1_11.png",
            tooltip: "<h3>Natural Dormancy</h3><hr style='margin-bottom:4px'>Unlock golden grass.<br><br>Reward: Increase grass value by 25%.",
            color: "white",
            complete() {return hasMilestone('r', 15) || hasMilestone("ip", 11)},
            unlocked: true,
            marked: true,
        },
        12: {
            name: "Golden Scam",
            image: "resources/achievements/1_12.png",
            tooltip: "<h3>Golden Scam</h3><hr style='margin-bottom:4px'>Increase your golden grass value.<br><br>Reward: Golden grass spawn time<br>reduced by 10%.",
            color: "white",
            complete() {return hasMilestone('r', 13)},
            unlocked: true,
            marked: true,
        },
        13: {
            name: "Bugged Buffs",
            image: "resources/achievements/1_13.png",
            tooltip: "<h3>Bugged Buffs</h3><hr style='margin-bottom:4px'>Do your first grasshop reset.",
            color: "white",
            unlocked: true,
        },
        14: {
            name: "Unranked",
            image: "resources/achievements/1_14.png",
            tooltip: "<h3>Unranked</h3><hr style='margin-bottom:4px'>Prestige without having any<br>ranks/tiers/tetrs.<br><br>Reward: Increase grass value<br>by 50%.",
            color: "white",
            complete() {return hasMilestone('r', 15) || hasMilestone("ip", 11)},
            unlocked: true,
            marked: true,
        },
        15: {
            name: "Small Returns",
            image: "resources/achievements/1_15.png",
            tooltip: "<h3>Small Returns</h3><hr style='margin-bottom:4px'>Buy a grass factor.<br><br>Reward: Increase fertilizer<br>gain by 50%.",
            color: "white",
            complete() {return hasMilestone("r", 16) || hasUpgrade("cs", 201)},
            unlocked: true,
            marked: true,
        },
        16: {
            name: "Shockingly Powerful",
            image: "resources/achievements/1_16.png",
            tooltip: "<h3>Shockingly Powerful</h3><hr style='margin-bottom:4px'>Buy a Factor Study I.",
            color: "white",
            complete() {return hasMilestone("ip", 17)},
            unlocked: true,
        },
        17: {
            name: "Hello World",
            image: "resources/achievements/1_17.png",
            tooltip: "<h3>Hello World</h3><hr style='margin-bottom:4px'>Do your first<br>code experience reset.<br><br>Reward: Decrease pent<br>requirement by /8.",
            color: "white",
            unlocked: true,
            marked: true,
        },
        18: {
            name: "Timed Gains",
            image: "resources/achievements/1_18.png",
            tooltip: "<h3>Timed Gains</h3><hr style='margin-bottom:4px'>Unlock Check Back.",
            color: "white",
            complete() {return hasMilestone("ip", 19) || hasMilestone("s", 17)},
            unlocked: true,
        },
        19: {
            name: "Lucky Gains",
            image: "resources/achievements/1_19.png",
            tooltip: "<h3>Lucky Gains</h3><hr style='margin-bottom:4px'>Enable dice OTF.",
            color: "white",
            unlocked: true,
        },
        20: {
            name: "Multiplied Chances",
            image: "resources/achievements/1_20.png",
            tooltip: "<h3>Multiplied Chances</h3><hr style='margin-bottom:4px'>Gain a second die.<br><br>Reward: Increase dice point<br>gain by 25%.",
            color: "white",
            complete() {return hasUpgrade("d", 11) || hasUpgrade("tad", 13)},
            unlocked: true,
            marked: true,
        },
        21: {
            name: "New Friends",
            image: "resources/achievements/1_21.png",
            tooltip: "<h3>New Friends</h3><hr style='margin-bottom:4px'>Gain your first pet.",
            color: "white",
            unlocked: true,
        },
        22: {
            name: "All In",
            image: "resources/achievements/1_22.png",
            tooltip: "<h3>All In</h3><hr style='margin-bottom:4px'>Have effect gain in<br>all tier 1 booster dice.<br><br>Reward: Unlock a toggle for<br>faster booster rolls.",
            color: "white",
            unlocked: true,
            marked: true,
        },
        23: {
            name: "Swarmed",
            image: "resources/achievements/1_23.png",
            tooltip: "<h3>Swarmed</h3><hr style='margin-bottom:4px'>Reset for over<br>1e25 grasshoppers<br><br>Reward: Double<br>grasshopper gain.",
            color: "white",
            unlocked: true,
            marked: true,
        },
        24: {
            name: "Pent-Uncapped",
            image: "resources/achievements/1_24.png",
            tooltip: "<h3>Pent-Uncapped</h3><hr style='margin-bottom:4px'>Gain a 31st pent.",
            color: "white",
            complete() {return hasUpgrade("i", 32) || inChallenge("ip", 14)},
            unlocked: true,
        },

        101: {
            name: "To Infinity",
            image: "resources/achievements/2_01.png",
            tooltip: "<h3>To Infinity</h3><hr style='margin-bottom:4px'>Reach infinity.",
            color: "#ffbf00",
            unlocked: true,
        },
    },
    tooltip: "Achievements",
    color: "white",
    microtabs: {
        stars: {
            1: {
                unlocked: true,
                content: [
                    ["top-column", [
                        ["row", [
                            ["achievement", 1], ["achievement", 2], ["achievement", 3], ["achievement", 4], ["achievement", 5], ["achievement", 6],
                            ["achievement", 7], ["achievement", 8], ["achievement", 9], ["achievement", 10], ["achievement", 11], ["achievement", 12],
                            ["achievement", 13], ["achievement", 14], ["achievement", 15], ["achievement", 16], ["achievement", 17], ["achievement", 18],
                            ["achievement", 19], ["achievement", 20], ["achievement", 21], ["achievement", 22], ["achievement", 23], ["achievement", 24],
                        ]],
                    ], {width: "621px", height: "409px", background: "#111", borderLeft: "3px solid white", padding: "3px", borderRadius: "0 0 22px 0"}],
                ],
            },
            2: {
                unlocked() {return hasAchievement("achievements", 101) || player.in.unlockedInfinity},
                content: [
                    ["top-column", [
                        ["row", [
                            ["achievement", 101],
                        ]],
                    ], {width: "621px", height: "409px", background: "#191300", borderLeft: "3px solid white", padding: "3px", borderRadius: "0 0 22px 0"}],
                ],
            },
        },
    },
    tabFormat: [
        ["style-column", [
            ["raw-html", "Achievements", {color: "white", fontSize: "30px", fontFamily: "monospace"}],
        ], {width: "800px", height: "50px", backgroundColor: "rgba(0,0,0,0.3)", borderTop: "3px solid white", borderLeft: "3px solid white", borderRight: "3px solid white", borderRadius: "25px 25px 0 0"}],
        ["style-row", [
            ["always-scroll-column", [
                ["style-row", [
                    ["category-button", ["☆", "stars", 1], {width: "155px", height: "40px", background: "#333", borderRight: "3px solid white"}],
                ], {width: "155px", height: "40px", borderBottom: "3px solid white"}],
                ["style-row", [
                    ["category-button", ["☆☆", "stars", 2], {width: "155px", height: "40px", background: "#332600", borderRight: "3px solid white"}],
                ], () => {return hasAchievement("achievements", 101) || player.in.unlockedInfinity ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
            ], {width: "170px", height: "415px"}],
            ["style-column", [
                ["buttonless-microtabs", "stars", {borderWidth: "0"}],
            ], {width: "630px", height: "415px"}],
        ], {width: "800px", height: "415px", backgroundColor: "black", border: "3px solid white", borderRadius: "0 0 25px 25px"}],
        ["blank", "25px"],
    ],
    layerShown() { return false }
})