// Sadly a necessary addition to the code
BHP.none = {
    name: "None",
    color: "#333",
    icon: "resources/secret.png",
    health: new Decimal(0),
    damage: new Decimal(0),
    defense: new Decimal(0),
    regen: new Decimal(0),
    agility: new Decimal(0),
    luck: new Decimal(0),
    mending: new Decimal(0),
}
BHP.general = {
    name: "Player",
    color: "#666",
    icon: "resources/player.png",
    health: new Decimal(100),
    damage: new Decimal(10),
    defense: new Decimal(10),
    regen: new Decimal(1),
    agility: new Decimal(10),
    luck: new Decimal(10),
    mending: new Decimal(0),
}
// Start of characters
BHP.kres = {
    name: "Kres",
    color: "#910a27",
    icon: "resources/kres.png",
    health: new Decimal(80),
    damage: new Decimal(6),
    defense: new Decimal(0),
    regen: new Decimal(0),
    agility: new Decimal(5),
    luck: new Decimal(0),
    mending: new Decimal(0),
}
BHP.nav = {
    name: "Nav",
    color: "#710a91",
    icon: "resources/nav.png",
    health: new Decimal(50),
    damage: new Decimal(8),
    defense: new Decimal(0),
    regen: new Decimal(0),
    agility: new Decimal(5),
    luck: new Decimal(0),
    mending: new Decimal(10),
}
BHP.sel = {
    name: "Sel",
    color: "#065c19",
    icon: "resources/sel.png",
    health: new Decimal(65),
    damage: new Decimal(4),
    defense: new Decimal(0),
    regen: new Decimal(0),
    agility: new Decimal(8),
    luck: new Decimal(0),
    mending: new Decimal(0),
}
BHP.eclipse = {
    name: "Eclipse",
    color: "#b68c18",
    icon: "resources/eclipse.png",
    health: new Decimal(100),
    damage: new Decimal(10),
    defense: new Decimal(10),
    regen: new Decimal(0),
    agility: new Decimal(0),
    luck: new Decimal(0),
    mending: new Decimal(5),
}
BHP.geroa = {
    name: "Geroa",
    color: "#536bdb",
    icon: "resources/geroa.png",
    health: new Decimal(50),
    damage: new Decimal(5),
    defense: new Decimal(5),
    regen: new Decimal(0.5),
    agility: new Decimal(10),
    luck: new Decimal(0),
    mending: new Decimal(5),
}